model:
  model_name: "tiiuae/falcon-7b"
  model_config:
  quant_config:
    load_in_4bit: true
    bnb_4bit_quant_type: "nf4"
    bnb_4bit_use_double_quant: true
    bnb_4bit_compute_dtype: "torch.bfloat16"
task_type: "CAUSAL_LM"
peft:
  type: "lora"
  peft_config:
    lora_alpha: 16
    lora_dropout: 0.05
    r: 8
    bias: "none"
    target_modules:
      - "query_key_value"
      - "dense"
      - "dense_h_to_4h"
      - "dense_4h_to_h"

data:
  data_location: "local"
  train_data: "test.csv"
  eval_data:
token:
  max_length:
  truncation: false
  padding: false
train:
  type: "trainer"
  final_save_path: "./falcon7B"
  train_config:
    per_device_train_batch_size: 1
    learning_rate: 0.0003
    gradient_accumulation_steps: 4
    save_steps: 1
    logging_steps: 1
    max_grad_norm: 1
    num_train_epochs: 5
    warmup_ratio: 0.03
    lr_scheduler_type: "constant"
    report_to:
    disable_tqdm: true
    group_by_length: true
    fp16: true
    optim: "adamw_bnb_8bit"